<?php
/**
 * Gutenverse Team content.
 */
return array(
	'title'      => __( 'Gutenverse Team', 'zeever' ),
	'categories' => array( 'zeever-gutenverse' ),
	'content'    => '
            <!-- wp:gutenverse/section {"layout":"fullwidth","gap":"no","elementId":"guten-Kkoj10","background":{"type":"default","color":{"r":18,"g":18,"b":18,"a":1}},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"120"}},"Tablet":{"unit":"px","dimension":{"bottom":"80","left":"10","right":"10"}},"Mobile":{}}} -->
            <div class="section-wrapper" data-id="Kkoj10"><script>var topKkoj10 = {"Desktop":{"point":"0","unit":"px"}};var bottomKkoj10 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-Kkoj10 layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":50},"elementId":"guten-3e5E6Z","margin":{"Desktop":{"unit":"px","dimension":{"left":"10","right":"10"}}},"padding":{"Desktop":{}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-3e5E6Z"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3e5E6Z"><script>var top3e5E6Z = {"Desktop":{"point":"0","unit":"px"}};var bottom3e5E6Z = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-DQMxmt","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":297,"image":"' . esc_url( ZEEVER_URI ) . 'assets/img/face-eyewear-glasses-green-blue-head-1493723-pxhere.com.webp"},"name":"Jonathan Doe","job":"Digital Marketing","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"","unit":"px"}},"weight":"500"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"jobTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"","unit":"px"}},"weight":"400"},"descColor":{"r":255,"g":255,"b":255,"a":1},"alignment":{"Tablet":null},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"imgWidth":{"Tablet":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":"100"},"Desktop":{"point":"","unit":"px"}},"imgHeight":{"Desktop":{"point":"460","unit":"px"},"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"hoverPadding":{"Tablet":{}},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"},"hoverContentBorder":{"radius":{"Tablet":{}}}} -->
            <div class="wp-block-gutenverse-team guten-element guten-team guten-DQMxmt"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( ZEEVER_URI ) . 'assets/img/face-eyewear-glasses-green-blue-head-1493723-pxhere.com.webp" alt="Jonathan Doe"/><div class="profile-body bottom"><h3 class="profile-title ">Jonathan Doe</h3><p class="profile-sub">Digital Marketing</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-9hrXzV","iconSize":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":0},"iconBorder":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"r":102,"g":252,"b":241,"a":1}}},"iconBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"border":{"radius":{"Desktop":{}}},"itemPadding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"hoverIconColor":{"r":8,"g":34,"b":34,"a":1},"hoverBgColor":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{}}} -->
            <div class="guten-element guten-social-icons guten-9hrXzV circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-WeoRYA"} -->
            <div class="guten-element guten-social-icon guten-WeoRYA facebook"><a id="guten-WeoRYA"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-kBOxHe"} -->
            <div class="guten-element guten-social-icon guten-kBOxHe twitter"><a id="guten-kBOxHe"><i class="fab fa-twitter"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-92PIgK"} -->
            <div class="guten-element guten-social-icon guten-92PIgK instagram"><a id="guten-92PIgK"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon --></div>
            <!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
            <!-- /wp:gutenverse/team --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":50},"elementId":"guten-XCdrQf","margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}}},"padding":{"Desktop":{}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-XCdrQf"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="XCdrQf"><script>var topXCdrQf = {"Desktop":{"point":"0","unit":"px"}};var bottomXCdrQf = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-OX0kUn","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":299,"image":"' . esc_url( ZEEVER_URI ) . 'assets/img/plaid-clothing-pattern-dress-shirt-cool-street-fashion-1513593-pxhere.com.webp"},"name":"Christopher Doe","job":"Web Developer","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"500"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"jobTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"descColor":{"r":255,"g":255,"b":255,"a":1},"alignment":{"Tablet":null},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"2","right":"2","bottom":"2","left":"2"}},"Mobile":{}},"profileBorder":{"radius":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{},"Mobile":{}},"imgWidth":{"Tablet":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":"100"},"Desktop":{"point":"","unit":"px"}},"imgHeight":{"Desktop":{"point":"460","unit":"px"},"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"}} -->
            <div class="wp-block-gutenverse-team guten-element guten-team guten-OX0kUn"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( ZEEVER_URI ) . 'assets/img/plaid-clothing-pattern-dress-shirt-cool-street-fashion-1513593-pxhere.com.webp" alt="Christopher Doe"/><div class="profile-body bottom"><h3 class="profile-title ">Christopher Doe</h3><p class="profile-sub">Web Developer</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-4Vxlya","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":0},"iconBorder":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"r":102,"g":252,"b":241,"a":1}}},"iconBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"border":{"radius":{"Desktop":{}}},"itemPadding":{},"hoverIconColor":{"r":8,"g":34,"b":34,"a":1},"hoverBgColor":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":{}}} -->
            <div class="guten-element guten-social-icons guten-4Vxlya circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-wQRVvm"} -->
            <div class="guten-element guten-social-icon guten-wQRVvm facebook"><a id="guten-wQRVvm"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-7VZADO"} -->
            <div class="guten-element guten-social-icon guten-7VZADO twitter"><a id="guten-7VZADO"><i class="fab fa-twitter"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-vUQkO0"} -->
            <div class="guten-element guten-social-icon guten-vUQkO0 instagram"><a id="guten-vUQkO0"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon --></div>
            <!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
            <!-- /wp:gutenverse/team --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":50},"elementId":"guten-ae55nh","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{},"Tablet":{}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-ae55nh"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ae55nh"><script>var topae55nh = {"Desktop":{"point":"0","unit":"px"}};var bottomae55nh = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-mlBErr","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":288,"image":"' . esc_url( ZEEVER_URI ) . 'assets/img/person-girl-woman-model-spring-fashion-110400-pxhere.com.webp"},"name":"Chintya Doe","job":"Talent Management","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"500"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"jobTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"descColor":{"r":255,"g":255,"b":255,"a":1},"alignment":{"Tablet":null},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"imgWidth":{"Tablet":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":"100"},"Desktop":{"point":"","unit":"px"}},"imgHeight":{"Desktop":{"point":"460","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"}} -->
            <div class="wp-block-gutenverse-team guten-element guten-team guten-mlBErr"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( ZEEVER_URI ) . 'assets/img/person-girl-woman-model-spring-fashion-110400-pxhere.com.webp" alt="Chintya Doe"/><div class="profile-body bottom"><h3 class="profile-title ">Chintya Doe</h3><p class="profile-sub">Talent Management</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-oAKPgJ","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":0},"iconBorder":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"r":102,"g":252,"b":241,"a":1}}},"iconBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"border":{"radius":{"Desktop":{}}},"itemPadding":{},"hoverIconColor":{"r":8,"g":34,"b":34,"a":1},"hoverBgColor":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":{}}} -->
            <div class="guten-element guten-social-icons guten-oAKPgJ circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-LOXbwz"} -->
            <div class="guten-element guten-social-icon guten-LOXbwz facebook"><a id="guten-LOXbwz"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-q9PAUt"} -->
            <div class="guten-element guten-social-icon guten-q9PAUt twitter"><a id="guten-q9PAUt"><i class="fab fa-twitter"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-nVh333"} -->
            <div class="guten-element guten-social-icon guten-nVh333 instagram"><a id="guten-nVh333"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon --></div>
            <!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
            <!-- /wp:gutenverse/team --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":50},"elementId":"guten-QLT6qO","margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{},"Tablet":{}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-QLT6qO"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="QLT6qO"><script>var topQLT6qO = {"Desktop":{"point":"0","unit":"px"}};var bottomQLT6qO = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-7lBszl","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":295,"image":"' . esc_url( ZEEVER_URI ) . 'assets/img/work-person-people-girl-woman-isolated-1258806-pxhere.com.webp"},"name":"Jennifer Doe","job":"Marketing","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"500"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"jobTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"descColor":{"r":255,"g":255,"b":255,"a":1},"alignment":{"Tablet":null},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"imgWidth":{"Tablet":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":"100"},"Desktop":{"point":"","unit":"px"}},"imgHeight":{"Desktop":{"point":"460","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"}} -->
            <div class="wp-block-gutenverse-team guten-element guten-team guten-7lBszl"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( ZEEVER_URI ) . 'assets/img/work-person-people-girl-woman-isolated-1258806-pxhere.com.webp" alt="Jennifer Doe"/><div class="profile-body bottom"><h3 class="profile-title ">Jennifer Doe</h3><p class="profile-sub">Marketing</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-jjfR5i","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":0},"iconBorder":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"r":102,"g":252,"b":241,"a":1}}},"iconBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"border":{"radius":{"Desktop":{}}},"itemPadding":{},"hoverIconColor":{"r":8,"g":34,"b":34,"a":1},"hoverBgColor":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":{}}} -->
            <div class="guten-element guten-social-icons guten-jjfR5i circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-JM0rBf"} -->
            <div class="guten-element guten-social-icon guten-JM0rBf facebook"><a id="guten-JM0rBf"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-Y6xBNF"} -->
            <div class="guten-element guten-social-icon guten-Y6xBNF twitter"><a id="guten-Y6xBNF"><i class="fab fa-twitter"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-Zy9zxI"} -->
            <div class="guten-element guten-social-icon guten-Zy9zxI instagram"><a id="guten-Zy9zxI"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon --></div>
            <!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
            <!-- /wp:gutenverse/team --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":20,"Tablet":100},"elementId":"guten-RiuPND","margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{},"Mobile":{}},"hideTablet":true} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-RiuPND hide-tablet"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="RiuPND"><script>var topRiuPND = {"Desktop":{"point":"0","unit":"px"}};var bottomRiuPND = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-38EhTA","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":300,"image":"' . esc_url( ZEEVER_URI ) . 'assets/img/street-fashion-photograph-blue-clothing-jeans-turquoise-1532253-pxhere.com.webp"},"name":"Marcho Doe","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"500"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"jobTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"descColor":{"r":255,"g":255,"b":255,"a":1},"alignment":{"Tablet":null},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"2","right":"2","bottom":"2","left":"2"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"imgWidth":{"Tablet":{"point":"240","unit":"px"},"Mobile":{"unit":"%","point":"100"},"Desktop":{"point":"","unit":"px"}},"imgHeight":{"Desktop":{"point":"460","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"}} -->
            <div class="wp-block-gutenverse-team guten-element guten-team guten-38EhTA"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( ZEEVER_URI ) . 'assets/img/street-fashion-photograph-blue-clothing-jeans-turquoise-1532253-pxhere.com.webp" alt="Marcho Doe"/><div class="profile-body bottom"><h3 class="profile-title ">Marcho Doe</h3><p class="profile-sub">Designer</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-8aLkY2","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":255,"g":255,"b":255,"a":0},"iconBorder":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"r":102,"g":252,"b":241,"a":1}}},"iconBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"border":{"radius":{"Desktop":{}}},"itemPadding":{},"hoverIconColor":{"r":8,"g":34,"b":34,"a":1},"hoverBgColor":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":{}}} -->
            <div class="guten-element guten-social-icons guten-8aLkY2 circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-C3IEEr"} -->
            <div class="guten-element guten-social-icon guten-C3IEEr facebook"><a id="guten-C3IEEr"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-4JkMRD"} -->
            <div class="guten-element guten-social-icon guten-4JkMRD twitter"><a id="guten-4JkMRD"><i class="fab fa-twitter"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon -->
            
            <!-- wp:gutenverse/social-icon {"elementId":"guten-0ad1PA"} -->
            <div class="guten-element guten-social-icon guten-0ad1PA instagram"><a id="guten-0ad1PA"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
            <!-- /wp:gutenverse/social-icon --></div>
            <!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
            <!-- /wp:gutenverse/team --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
