<?php
/**
 * Gutenverse Our Skills content.
 */
return array(
	'title'      => __( 'Gutenverse Our Skills', 'zeever' ),
	'categories' => array( 'zeever-gutenverse' ),
	'content'    => '
            <!-- wp:gutenverse/section {"width":{"Desktop":1170},"elementId":"guten-Dprc0W","background":{"type":"default","color":{"r":18,"g":18,"b":18,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"","bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}},"animation":{"type":{"Desktop":"none"}}} -->
            <div class="section-wrapper" data-id="Dprc0W"><script>var topDprc0W = {"Desktop":{"point":"0","unit":"px"}};var bottomDprc0W = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-Dprc0W layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-j6ojyR","border":{"radius":{"Desktop":{}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-j6ojyR"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="j6ojyR"><script>var topj6ojyR = {"Desktop":{"point":"0","unit":"px"}};var bottomj6ojyR = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-sK0EZN"} -->
            <div class="section-wrapper" data-id="sK0EZN"><script>var topsK0EZN = {"Desktop":{"point":"0","unit":"px"}};var bottomsK0EZN = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-sK0EZN layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"elementId":"guten-UyU4sb","margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-UyU4sb"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="UyU4sb"><script>var topUyU4sb = {"Desktop":{"point":"0","unit":"px"}};var bottomUyU4sb = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-5HbOWr","color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"spacing":{"Desktop":""},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"transform":"capitalize"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"80"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-5HbOWr animated guten-element-hide desktop-fadeInLeft">Here are some of our great skills</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/text-editor {"elementId":"guten-pUn1hd","columns":{"Desktop":"1"},"textColor":{"r":208,"g":208,"b":208,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"15","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"100","bottom":"20","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{}}} -->
            <div class="guten-element gutenverse-text-editor guten-pUn1hd"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor -->
            
            <!-- wp:gutenverse/progress-bar {"elementId":"guten-Z3dpAf","title":"UI Design","percentage":"91","barColor":{"r":37,"g":37,"b":37,"a":1},"trackColor":{"r":102,"g":252,"b":241,"a":1},"trackHeight":{"Desktop":"5"},"barRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"barPadding":{"Desktop":{}},"barMargin":{"Desktop":{}},"titleColor":{"r":255,"g":255,"b":255,"a":1},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"600"},"percentColor":{"r":208,"g":208,"b":208,"a":1},"percentTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"}} -->
            <div class="guten-element guten-progress-bar guten-Z3dpAf"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">UI Design</span></div><div class="skill-bar"><div class="skill-track" data-width="91" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
            <!-- /wp:gutenverse/progress-bar -->
            
            <!-- wp:gutenverse/progress-bar {"elementId":"guten-76TLLi","title":" Digital Strategy","percentage":"94","barColor":{"r":37,"g":37,"b":37,"a":1},"trackColor":{"r":102,"g":252,"b":241,"a":1},"trackHeight":{"Desktop":"5"},"barRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"barPadding":{"Desktop":{}},"barMargin":{"Desktop":{}},"titleColor":{"r":255,"g":255,"b":255,"a":1},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"600"},"percentColor":{"r":208,"g":208,"b":208,"a":1},"percentTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{}}} -->
            <div class="guten-element guten-progress-bar guten-76TLLi"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title"> Digital Strategy</span></div><div class="skill-bar"><div class="skill-track" data-width="94" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
            <!-- /wp:gutenverse/progress-bar -->
            
            <!-- wp:gutenverse/progress-bar {"elementId":"guten-np7sUQ","title":" Content Writing","percentage":"89","barColor":{"r":37,"g":37,"b":37,"a":1},"trackColor":{"r":102,"g":252,"b":241,"a":1},"trackHeight":{"Desktop":"5"},"barRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"barPadding":{"Desktop":{}},"barMargin":{"Desktop":{}},"titleColor":{"r":255,"g":255,"b":255,"a":1},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"600"},"percentColor":{"r":208,"g":208,"b":208,"a":1},"percentTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{}}} -->
            <div class="guten-element guten-progress-bar guten-np7sUQ"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title"> Content Writing</span></div><div class="skill-bar"><div class="skill-track" data-width="89" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
            <!-- /wp:gutenverse/progress-bar -->
            
            <!-- wp:gutenverse/progress-bar {"elementId":"guten-QNRhTO","title":"Social Media","percentage":"92","barColor":{"r":37,"g":37,"b":37,"a":1},"trackColor":{"r":102,"g":252,"b":241,"a":1},"trackHeight":{"Desktop":"5"},"barRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"barPadding":{"Desktop":{}},"barMargin":{"Desktop":{}},"titleColor":{"r":255,"g":255,"b":255,"a":1},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"600"},"percentColor":{"r":208,"g":208,"b":208,"a":1},"percentTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{}}} -->
            <div class="guten-element guten-progress-bar guten-QNRhTO"><div class="progress-group"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Social Media</span></div><div class="skill-bar"><div class="skill-track" data-width="92" data-duration="3500"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
            <!-- /wp:gutenverse/progress-bar --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-dBWwNb","background":{"type":"default","image":{"Desktop":{"id":98,"image":"' . esc_url( ZEEVER_URI ) . 'assets/img/employee-meeting-work-job-working-argentina-1599048-pxhere.com.webp"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover"}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"60"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-dBWwNb"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="dBWwNb"><script>var topdBWwNb = {"Desktop":{"point":"0","unit":"px"}};var bottomdBWwNb = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-CbBwDv","space":{"Mobile":{"point":"320","unit":"px"}},"margin":{"Mobile":{"unit":"px","dimension":{"top":""}}},"padding":{"Mobile":{}}} -->
            <div class="guten-element guten-spacer guten-CbBwDv"></div>
            <!-- /wp:gutenverse/spacer --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
