<?php
/**
 * Gutenverse Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Hero', 'zeever' ),
	'categories' => array( 'zeever-gutenverse' ),
	'content'    => '
            <!-- wp:gutenverse/section {"width":{"Desktop":1170},"elementId":"guten-P6sVWZ","background":{"type":"default","image":{"Desktop":{"id":71,"image":"' . esc_url( ZEEVER_URI ) . 'assets/img/background.webp"}},"position":{"Desktop":"top center","Tablet":"center center"},"size":{"Desktop":"custom","Tablet":"cover"},"repeat":{"Desktop":"no-repeat"},"yposition":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"200","unit":"px"}},"xposition":{"Desktop":{"point":"","unit":"px"},"Tablet":{"unit":"px","point":"100"}},"width":{"Desktop":{"unit":"%","point":"85"},"Tablet":{"unit":"%","point":"100"}},"color":{"r":0,"g":0,"b":1,"a":1}},"backgroundOverlay":{"type":"default","color":{"r":1,"g":1,"b":1,"a":1},"gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":3,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","id":7,"offset":"0.107","active":false},{"color":"rgba(255, 255, 255, 0)","active":true,"id":6,"offset":"0.190"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":5,"offset":"0.293"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":4,"offset":"0.937"}],"gradientType":"linear","gradientAngle":270},"opacity":"0.1","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"300","bottom":"180"}},"Tablet":{"unit":"px","dimension":{"top":"220","bottom":"120","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"bottom":"80","top":"180"}}},"zIndex":{"Desktop":"2"}} -->
            <div class="section-wrapper" data-id="P6sVWZ"><script>var topP6sVWZ = {"Desktop":{"point":"0","unit":"px"}};var bottomP6sVWZ = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-P6sVWZ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":55.99,"Tablet":68},"elementId":"guten-91Fk0O","margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-91Fk0O"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="91Fk0O"><script>var top91Fk0O = {"Desktop":{"point":"0","unit":"px"}};var bottom91Fk0O = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-0iCbAc","textColor":{"r":194,"g":186,"b":176,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"80","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
            <div class="guten-element gutenverse-text-editor guten-0iCbAc"><div class="text-content-inner"><!-- wp:gutenverse/heading {"elementId":"guten-CqbjQ5","type":5,"color":{"r":102,"g":252,"b":241,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"500"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"slow"}} -->
            <h5 class="wp-block-gutenverse-heading guten-element guten-CqbjQ5 animated guten-element-hide slow desktop-fadeInLeft">CREATIVE MIND, CREATIVE WORKS.</h5>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/heading {"elementId":"guten-XvGz0E","type":1,"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"76","unit":"px"},"Mobile":{"point":"31","unit":"px"}},"weight":"600","spacing":{"Desktop":""},"transform":"default","decoration":"none","style":"normal"},"background":{"type":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"30"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"slow"}} -->
            <h1 class="wp-block-gutenverse-heading guten-element guten-XvGz0E animated guten-element-hide slow desktop-fadeInLeft">We Are Digital Agency</h1>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/button {"elementId":"guten-BTgZlT","content":"Getting Started","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"23","right":"30","bottom":"23","left":"30"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","top":"18","bottom":"18"}}},"buttonBackground":{"type":"default","color":{"r":145,"g":108,"b":61,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"2","color":{"r":102,"g":252,"b":241,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"2","color":{"r":74,"g":189,"b":180,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"60"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"slow","delay":"40"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"15","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"500"},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1}} -->
            <div class="guten-element guten-button-wrapper guten-BTgZlT"><a class="guten-button animated guten-element-hide slow desktop-fadeInLeft guten-button-sm" href="#"><span>Getting Started</span></a></div>
            <!-- /wp:gutenverse/button --></div></div>
            <!-- /wp:gutenverse/text-editor --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":44.01,"Tablet":null,"Mobile":null},"elementId":"guten-lpET5f","hideMobile":true} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-lpET5f hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="lpET5f"><script>var toplpET5f = {"Desktop":{"point":"0","unit":"px"}};var bottomlpET5f = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
