<?php
/**
 * Gutenverse Best Solution content.
 */
return array(
	'title'      => __( 'Gutenverse Best Solution', 'zeever' ),
	'categories' => array( 'zeever-gutenverse' ),
	'content'    => '
            <!-- wp:gutenverse/section {"width":{"Desktop":1170},"elementId":"guten-H8d2EO","verticalAlign":"center","background":{"type":"default","color":{"r":0,"g":0,"b":1,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}},"animation":{"type":{"Desktop":"none"}}} -->
            <div class="section-wrapper" data-id="H8d2EO"><script>var topH8d2EO = {"Desktop":{"point":"0","unit":"px"}};var bottomH8d2EO = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-H8d2EO layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-AoWPJO","border":{"radius":{"Desktop":{}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-AoWPJO"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="AoWPJO"><script>var topAoWPJO = {"Desktop":{"point":"0","unit":"px"}};var bottomAoWPJO = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-PVvNz3"} -->
            <div class="section-wrapper" data-id="PVvNz3"><script>var topPVvNz3 = {"Desktop":{"point":"0","unit":"px"}};var bottomPVvNz3 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-PVvNz3 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-6v8Nk9","background":{"type":"default","image":{"Desktop":{"id":99,"image":"' . esc_url( ZEEVER_URI ) . 'assets/img/employee-meeting-work-job-working-argentina-1599057-pxhere.com.webp"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover"}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"20","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"40","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-6v8Nk9"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="6v8Nk9"><script>var top6v8Nk9 = {"Desktop":{"point":"0","unit":"px"}};var bottom6v8Nk9 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-PPRAWw","space":{"Desktop":{"point":"540","unit":"px"},"Mobile":{"point":"320","unit":"px"}}} -->
            <div class="guten-element guten-spacer guten-PPRAWw"></div>
            <!-- /wp:gutenverse/spacer --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-C2FamW","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"60"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-C2FamW"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="C2FamW"><script>var topC2FamW = {"Desktop":{"point":"0","unit":"px"}};var bottomC2FamW = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-rOTdRc","color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"spacing":{"Desktop":""},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"transform":"capitalize"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
            <h2 class="wp-block-gutenverse-heading guten-element guten-rOTdRc animated guten-element-hide desktop-fadeInRight">Best Solutions for Your Business</h2>
            <!-- /wp:gutenverse/heading -->
            
            <!-- wp:gutenverse/text-editor {"elementId":"guten-H5rWBY","columns":{"Desktop":"1"},"textColor":{"r":208,"g":208,"b":208,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"15","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"100","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}}} -->
            <div class="guten-element gutenverse-text-editor guten-H5rWBY"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.</p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor -->
            
            <!-- wp:gutenverse/button {"elementId":"guten-BTgZlT","content":"Watch Video","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"23","right":"30","bottom":"23","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"20","left":"20"}}},"buttonBackground":{"type":"default","color":{"r":145,"g":108,"b":61,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"2","color":{"r":102,"g":252,"b":241,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"2","color":{"r":74,"g":189,"b":180,"a":1}}},"showIcon":true,"icon":"gtn gtn-play-button","iconSpacing":{"Desktop":"14"},"iconSize":{"Desktop":{"point":"14","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"color":{"r":255,"g":255,"b":255,"a":1},"iconColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"500"},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1}} -->
            <div class="guten-element guten-button-wrapper guten-BTgZlT"><a class="guten-button guten-button-sm" href="#"><i class="fa-lg gtn gtn-play-button"></i><span>Watch Video</span></a></div>
            <!-- /wp:gutenverse/button --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
