<?php
/**
 * Gutenverse FAQ content.
 */
return array(
	'title'      => __( 'Gutenverse FAQ', 'zeever' ),
	'categories' => array( 'zeever-gutenverse' ),
	'content'    => '
            <!-- wp:gutenverse/section {"width":{"Desktop":1170},"elementId":"guten-Dprc0W","background":{"type":"default","color":{"r":11,"g":12,"b":16,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"80","bottom":"40"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"20"}}},"animation":{"type":{"Desktop":"none"}}} -->
            <div class="section-wrapper" data-id="Dprc0W"><script>var topDprc0W = {"Desktop":{"point":"0","unit":"px"}};var bottomDprc0W = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-Dprc0W layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-j6ojyR","border":{"radius":{"Desktop":{}}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-j6ojyR"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="j6ojyR"><script>var topj6ojyR = {"Desktop":{"point":"0","unit":"px"}};var bottomj6ojyR = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-sK0EZN"} -->
            <div class="section-wrapper" data-id="sK0EZN"><script>var topsK0EZN = {"Desktop":{"point":"0","unit":"px"}};var bottomsK0EZN = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-sK0EZN layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-dBWwNb","background":{"type":"default","image":{"Desktop":{"id":98,"image":"' . esc_url( ZEEVER_URI ) . 'assets/img/employee-meeting-work-job-working-argentina-1599048-pxhere.com.webp"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover"}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","right":"60"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Tablet":{}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-dBWwNb"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="dBWwNb"><script>var topdBWwNb = {"Desktop":{"point":"0","unit":"px"}};var bottomdBWwNb = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-CbBwDv","space":{"Tablet":{"point":"400","unit":"px"},"Mobile":{"point":"300","unit":"px"}}} -->
            <div class="guten-element guten-spacer guten-CbBwDv"></div>
            <!-- /wp:gutenverse/spacer --></div></div></div>
            <!-- /wp:gutenverse/column -->
            
            <!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-UyU4sb","margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}}} -->
            <div class="wp-block-gutenverse-column guten-element guten-column guten-UyU4sb"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="UyU4sb"><script>var topUyU4sb = {"Desktop":{"point":"0","unit":"px"}};var bottomUyU4sb = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-rDwWpK","alignText":{"Desktop":"flex-start"},"text":"FAQ.","focusText":"","subText":"Popular Question From Clients","lineWidth":{"Desktop":"12","Tablet":"","Mobile":""},"lineHeight":{"Desktop":"3"},"lineStyle":"solid","lineMargin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{}},"mainColor":{"r":255,"g":255,"b":255,"a":1},"mainTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Mobile":{"point":"30","unit":"px"}}},"mainBackground":{"type":"default","gradientColor":[{"color":"rgb(49, 207, 180)","id":1,"offset":"0.132","active":true},{"color":"rgb(126, 32, 207)","id":2,"offset":"1.000","active":false}],"color":""},"mainMargin":{"Desktop":{"unit":"px","dimension":{"right":"","bottom":"","top":""}},"Mobile":{}},"mainPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"focusBackground":{"type":"default","color":""},"focusMargin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"focusPadding":{"Desktop":{"unit":"px","dimension":{"top":"3","right":"3","bottom":"3","left":"3"}}},"subColor":{"r":102,"g":252,"b":241,"a":1},"subTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"500","transform":"uppercase"},"subMargin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":{}},"subPadding":{"Desktop":{},"Mobile":{}},"lineColor":{"r":102,"g":252,"b":241,"a":1},"background":{},"backgroundHover":{},"border":{},"boxShadow":{"position":"outline"},"borderHover":{},"boxShadowHover":{"position":"outline"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
            <div class="guten-element guten-advanced-heading guten-rDwWpK animated guten-element-hide desktop-fadeInRight"><div class="heading-section "><div class="heading-line before"></div><h2 class="heading-title">FAQ.<span class="heading-focus"></span></h2></div><span class="heading-subtitle">Popular Question From Clients</span></div>
            <!-- /wp:gutenverse/advanced-heading -->
            
            <!-- wp:gutenverse/text-editor {"elementId":"guten-pUn1hd","columns":{"Desktop":"1"},"textColor":{"r":208,"g":208,"b":208,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"15","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"100","bottom":"20","left":""}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
            <div class="guten-element gutenverse-text-editor guten-pUn1hd"><div class="text-content-inner"><!-- wp:paragraph -->
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
            <!-- /wp:paragraph --></div></div>
            <!-- /wp:gutenverse/text-editor -->
            
            <!-- wp:gutenverse/accordions {"elementId":"guten-MRbC1u","iconOpen":"fas fa-chevron-up","iconClosed":"fas fa-chevron-down","iconPosition":"right","iconColor":{"r":208,"g":208,"b":208,"a":1},"iconActiveColor":{"r":102,"g":252,"b":241,"a":1},"titleBackgroundColor":{"r":255,"g":255,"b":255,"a":0},"titleTextColor":{"r":255,"g":255,"b":255,"a":1},"titleActiveColor":{"r":255,"g":255,"b":255,"a":1},"titleTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"500","lineHeight":{"Mobile":{"unit":"em","point":"1.5"}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"25","right":"30","bottom":"25","left":"30"}},"Mobile":{"unit":"px","dimension":{"right":"20","top":"20","bottom":"20","left":"20"}}},"contentBackgroundColor":{"r":255,"g":255,"b":255,"a":0},"contentTextColor":{"r":208,"g":208,"b":208,"a":1},"contentTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"15","unit":"px"}}},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"right":""}}},"accordionBorder":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"r":208,"g":208,"b":208,"a":1}},"bottom":{"type":"none"},"top":{"type":"none"}},"titleBorder":{"radius":{"Desktop":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"r":208,"g":208,"b":208,"a":1}},"left":{"type":"none"},"right":{"type":"none"}},"contentBorder":{"radius":{"Desktop":{},"Mobile":{}},"all":{"type":"none","width":"1","color":{"r":102,"g":252,"b":241,"a":1}}},"background":{"type":"default","color":""},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":[],"Mobile":{}},"accordionBorderActive":{"radius":{"Desktop":{}},"all":{"type":"none"}},"accordionMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"30","top":"","right":"","left":""}}},"contentBorderActive":{"all":{"type":"solid","width":"1","color":{"r":102,"g":252,"b":241,"a":1}},"top":{"type":"none"},"radius":{"Desktop":{}}},"titleBorderActive":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"r":102,"g":252,"b":241,"a":1}}}} -->
            <div class="guten-element guten-accordions guten-MRbC1u"><!-- wp:gutenverse/accordion {"elementId":"guten-d3gEW4","iconOpen":"fas fa-chevron-up","iconClosed":"fas fa-chevron-down","iconPosition":"right"} -->
            <div class="accordion-item"><div class="accordion-heading"><span class="accordion-text">Where Can I Find More Information?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-chevron-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-chevron-down"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris</p>
            <!-- /wp:paragraph --></div></div></div>
            <!-- /wp:gutenverse/accordion -->
            
            <!-- wp:gutenverse/accordion {"elementId":"guten-YwNDj0","iconOpen":"fas fa-chevron-up","iconClosed":"fas fa-chevron-down","iconPosition":"right"} -->
            <div class="accordion-item"><div class="accordion-heading"><span class="accordion-text"><meta charset="utf-8">What Kinds of Payment Do You Accept?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-chevron-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-chevron-down"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
            <p><meta charset="utf-8">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris</p>
            <!-- /wp:paragraph --></div></div></div>
            <!-- /wp:gutenverse/accordion -->
            
            <!-- wp:gutenverse/accordion {"elementId":"guten-eQSKw4","first":true,"iconOpen":"fas fa-chevron-up","iconClosed":"fas fa-chevron-down","iconPosition":"right"} -->
            <div class="accordion-item active"><div class="accordion-heading"><span class="accordion-text">What Are Your Terms and Conditions?</span><div class="accordion-icon"><span class="accordion-icon-open"><i class="fas fa-chevron-up"></i></span><span class="accordion-icon-closed"><i class="fas fa-chevron-down"></i></span></div></div><div class="accordion-body"><div class="accordion-content"><!-- wp:paragraph -->
            <p><meta charset="utf-8">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris</p>
            <!-- /wp:paragraph --></div></div></div>
            <!-- /wp:gutenverse/accordion --></div>
            <!-- /wp:gutenverse/accordions --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section --></div></div></div>
            <!-- /wp:gutenverse/column --></div></section></div>
            <!-- /wp:gutenverse/section -->',
);
